"""Fix token column in Users table

Revision ID: 0835ff905757
Revises: 3afc456e4dd6
Create Date: 2025-03-17 22:18:20.470964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0835ff905757"
down_revision: Union[str, None] = "3afc456e4dd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_token_key", "users", type_="unique")
    op.drop_column("users", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.VARCHAR(length=350), autoincrement=False, nullable=True))
    op.create_unique_constraint("users_token_key", "users", ["token"])
    # ### end Alembic commands ###
