"""Fix token column in Users table

Revision ID: 0bbd72d88492
Revises: 209168c59cf3
Create Date: 2025-03-17 22:10:19.781009

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "0bbd72d88492"
down_revision: Union[str, None] = "209168c59cf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
