"""Fix token column in Users table

Revision ID: 209168c59cf3
Revises: 9c400e0a0364
Create Date: 2025-03-17 22:09:32.372647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "209168c59cf3"
down_revision: Union[str, None] = "9c400e0a0364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(length=350), nullable=True))
    op.create_unique_constraint(None, "users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "token")
    # ### end Alembic commands ###
