"""Fix token column in Users table

Revision ID: 3afc456e4dd6
Revises: d33f95c9e2c6
Create Date: 2025-03-17 22:12:05.205826

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "3afc456e4dd6"
down_revision: Union[str, None] = "d33f95c9e2c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
