"""added_user_roles

Revision ID: 4238fa4ad75a
Revises: 
Create Date: 2025-03-14 08:35:17.217863

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "4238fa4ad75a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
