"""Now token saves in token column in Users table

Revision ID: 4616146db8b7
Revises: 4238fa4ad75a
Create Date: 2025-03-17 21:58:46.325223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4616146db8b7"
down_revision: Union[str, None] = "4238fa4ad75a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(length=350), nullable=False))
    op.create_unique_constraint(None, "users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "token")
    # ### end Alembic commands ###
