"""Fix token column in Users table

Revision ID: 9c400e0a0364
Revises: ebc38577fe2c
Create Date: 2025-03-17 22:09:01.363196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c400e0a0364"
down_revision: Union[str, None] = "ebc38577fe2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(length=350), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token")
    # ### end Alembic commands ###
