"""Fix token column in Users table

Revision ID: 9de2a452e6f8
Revises: 0835ff905757
Create Date: 2025-03-17 22:19:16.629600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9de2a452e6f8"
down_revision: Union[str, None] = "0835ff905757"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(length=350), nullable=True))
    op.create_unique_constraint(None, "users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "token")
    # ### end Alembic commands ###
