"""Fix token column in Users table

Revision ID: d33f95c9e2c6
Revises: 0bbd72d88492
Create Date: 2025-03-17 22:10:45.958967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d33f95c9e2c6"
down_revision: Union[str, None] = "0bbd72d88492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "token",
               existing_type=sa.VARCHAR(length=350),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "token",
               existing_type=sa.VARCHAR(length=350),
               nullable=True)
    # ### end Alembic commands ###
