"""Fix token column in Users table

Revision ID: ebc38577fe2c
Revises: 4616146db8b7
Create Date: 2025-03-17 22:07:30.203084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebc38577fe2c"
down_revision: Union[str, None] = "4616146db8b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(length=350), server_default="", nullable=False))
    op.create_unique_constraint(None, "users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "token")
    # ### end Alembic commands ###
